In [1]:
import numpy as np

In [2]:
data = np.array([1, 3, 4, 4])
print(data)

print("Mean: ", np.mean(data))
print("Std: ", np.std(data))
print("Variance: ", np.var(data))

[1 3 4 4]
Mean:  3.0
Std:  1.224744871391589
Variance:  1.5


In [3]:
data = np.array([1, 2, 3, 2])
print(data)

print("Mean: ", np.mean(data))
print("Std: ", np.std(data))
print("Variance: ", np.var(data))

[1 2 3 2]
Mean:  2.0
Std:  0.7071067811865476
Variance:  0.5


In [4]:
# Sample data for two variables
var1 = np.array([1, 3, 4, 4])
var2 = np.array([1, 2, 3, 2])

# Compute covariance
print("Covariance: \n", np.cov(var1, var2))

# Compute correlation coefficient
print("Correlation: \n", np.corrcoef(var1, var2))

Covariance: 
 [[2.         1.        ]
 [1.         0.66666667]]
Correlation: 
 [[1.        0.8660254]
 [0.8660254 1.       ]]
