# Create a tensor

In [ ]:
import torch

data = [1, 2, 3]
data = torch.tensor(data)
print(data)

[tensor([1, 2, 3])]


In [2]:
import numpy as np 

data = np.array([1, 2, 3])
data = torch.from_numpy(data)
print(data)

tensor([1, 2, 3])


In [ ]:
data = torch.zeros(3, 3)
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
data = torch.full((3, 3), 9)
print(data)

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])


In [ ]:
data = torch.arange(start=0, end=5, step=1)
print(data)

tensor([0, 1, 2, 3, 4])


In [ ]:
# Creates a 3x3 tensor with 
# random values between 0 and 1
data = torch.rand(3, 3)
print(data)

tensor([[0.0961, 0.4473, 0.8793],
        [0.7239, 0.6152, 0.7515],
        [0.4577, 0.1414, 0.0398]])


In [10]:
# Creates a 3x3 tensor with random integers between 0 and 4
data = torch.randint(low=0, high=5, size=(3, 3))
print(data)

tensor([[3, 3, 1],
        [1, 3, 2],
        [2, 3, 1]])


In [11]:
# Creates a 3x3 tensor with values 
# sampled from a standard normal distribution
data = torch.randn(3, 3)
print(data) 

tensor([[-1.8008, -1.2007, -0.1652],
        [-0.1726, -0.3710,  1.7057],
        [ 0.9161, -0.4129,  1.1013]])


In [13]:
# broadcasting
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([1])

print(f"Tensor 1:\n {tensor1}")
print(f"Tensor 2:\n {tensor2}")

tensor3 = tensor1 + tensor2
print(f"Tensor3:\n {tensor3}")

Tensor 1:
 tensor([[1, 2],
        [3, 4]])
Tensor 2:
 tensor([1])
Tensor3:
 tensor([[2, 3],
        [4, 5]])


In [14]:
# broadcasting
import numpy as np

# create a tensor
tensor1 = torch.tensor([[1, 2], 
                        [3, 4]])
print(f'Tensor1:\n {tensor1}')

# Between a tensor and a number
tensor2 = tensor1 + 2
print(f'Tensor2:\n {tensor2}')

Tensor1:
 tensor([[1, 2],
        [3, 4]])
Tensor2:
 tensor([[3, 4],
        [5, 6]])


In [16]:
# Compute squared difference with broadcasting
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = 5

squared_diff = (x - y)**2

print(f"x: {x}")
print(f"y = {y}")
print(f"squared diff: {squared_diff}")

x: tensor([1., 2., 3., 4.])
y = 5
squared diff: tensor([16.,  9.,  4.,  1.])


In [17]:
# Compute squared difference
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = torch.tensor([5.0, 5.0, 5.0, 5.0])

loss_fn = torch.nn.MSELoss()
mse = loss_fn(x, y)

print(f"x: {x}")
print(f"y = {y}")
print(f"mse: {mse}")

x: tensor([1., 2., 3., 4.])
y = tensor([5., 5., 5., 5.])
mse: 7.5


In [18]:
# Concat
x = torch.tensor([
    [1, 2],
    [3, 4]
])

y = torch.tensor([
    [3, 4],
    [5, 6]
])

tensor1 = torch.cat((x, y), dim=0)
tensor2 = torch.cat((x, y), dim=1)
print(f"Tensor 1: {tensor1}")
print(f"Tensor 2: {tensor2}")

Tensor 1: tensor([[1, 2],
        [3, 4],
        [3, 4],
        [5, 6]])
Tensor 2: tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])


In [20]:
# argmax
# Creates a 3x2 tensor
data = torch.randint(low=0, high=9, size=(3, 2))
print(f'data:\n {data}')

# Compute argmax across the rows (dimension 0)
argmax_dim0 = torch.argmax(data, dim=0)
print(f'argmax1:\n {argmax_dim0}')

# Compute argmax across the columns (dimension 1)
argmax_dim1 = torch.argmax(data, dim=1)
print(f'argmax1:\n {argmax_dim1}')

data:
 tensor([[1, 7],
        [3, 1],
        [1, 3]])
argmax1:
 tensor([1, 0])
argmax1:
 tensor([1, 0, 1])


In [21]:
# autograd
# Create a tensor to compute gradients
x = torch.tensor(2.0, requires_grad=True)

# operation
y = x ** 2
z = 3*y + 2
print(f'z: {z}')

# Backpropagate to compute gradients
z.backward()

# Print the gradient. dz/dx at x=2.0
print(f"Gradient of z w.r.t. x: {x.grad}")

z: 14.0
Gradient of z w.r.t. x: 12.0
