In [25]:
import numpy as np
import time

In [34]:
original_array = np.arange(12)

original_array = original_array.reshape((3, 4))

print(original_array.shape)


(3, 4)


In [35]:
# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Sum across columns
column_sum = np.sum(array, axis=0)

print("Array:")
print(array)
print("\nSum across columns:", column_sum)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum across columns: [12 15 18]


In [36]:
# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

filtered_elements = array[(array > 2) & (array < 5)]

filtered_elements = filtered_elements[::-1]

print(filtered_elements)

[4 3]


In [37]:
# Create a 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

reshaped_array = original_array.reshape(-1)

print("Original array (2D):")
print(original_array)
print("\nReshaped array (1D):")
print(reshaped_array)


Original array (2D):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped array (1D):
[1 2 3 4 5 6 7 8 9]


In [38]:
# Create a 1D array
array1 = np.array([1, 2, 3])

# Create a 2D array
array2 = np.array([[4, 5, 6],
                   [7, 8, 9]])

result = array1 + array2

print(result)

[[ 5  7  9]
 [ 8 10 12]]


In [39]:
np.array([1, 2, 3]) + np.array([[1], [2], [3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [26]:
def multiplizeList(size=1000):
  # declaring lists
  list1 = list(range(size))
  list2 = list(range(size))

  # capturing time before the multiplication of Python lists
  initialTime = time.time()

  # multiplying elements of both the lists and stored in another list
  resultantList = [(a * b) for a, b in zip(list1, list2)]

  # calculating execution time
  print("Time taken by Lists to perform multiplication:",
    (time.time() - initialTime),
    "seconds")



def multiplizeArray(size=1000):
  # declaring arrays
  array1 = np.arange(size)
  array2 = np.arange(size)

  # capturing time before the multiplication of Numpy arrays
  initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
  resultantArray = array1 * array2

# calculating execution time
  print("Time taken by NumPy Arrays to perform multiplication:",
    (time.time() - initialTime),
    "seconds")

In [27]:
multiplizeList()
multiplizeArray()

Time taken by Lists to perform multiplication: 9.441375732421875e-05 seconds
Time taken by NumPy Arrays to perform multiplication: 2.5033950805664062e-05 seconds


In [31]:
# List solution
def compute_iou(box1, box2):
        x1_1, y1_1, x2_1, y2_1 = box1
        x1_2, y1_2, x2_2, y2_2 = box2

        # Compute the coordinates of the intersection rectangle
        xx1 = max(x1_1, x1_2)
        yy1 = max(y1_1, y1_2)
        xx2 = min(x2_1, x2_2)
        yy2 = min(y2_1, y2_2)

        # Compute the width and height of the intersection rectangle
        w = max(0, xx2 - xx1 + 1)
        h = max(0, yy2 - yy1 + 1)

        # Compute the area of the intersection rectangle
        inter_area = w * h

        # Compute the area of both bounding boxes
        box1_area = (x2_1 - x1_1 + 1) * (y2_1 - y1_1 + 1)
        box2_area = (x2_2 - x1_2 + 1) * (y2_2 - y1_2 + 1)

        # Compute the Intersection over Union (IoU)
        iou = inter_area / float(box1_area + box2_area - inter_area)

        return iou

# Refine for class
def non_max_suppression(boxes, scores, iou_threshold):


    # Sort the boxes by scores in descending order
    sorted_indices = sorted(range(len(scores)), key=lambda k: scores[k], reverse=True)

    keep = []  # List to store the indices of boxes to keep

    while sorted_indices:
        i = sorted_indices.pop(0)  # Index of the current highest score box
        keep.append(i)
        # print("sorted_indices", sorted_indices)
        filtered_indices = []
        for j in sorted_indices:
            iou = compute_iou(boxes[i], boxes[j])
            if iou <= iou_threshold:
                filtered_indices.append(j)

        sorted_indices = filtered_indices

    return keep

# Example usage
# boxes = [
#     [12, 84, 140, 212],
#     [24, 84, 152, 212],
#     [36, 84, 164, 212],
#     [12, 96, 140, 224],
#     [24, 96, 152, 224]
# ]

# scores = [0.3, 0.4, 0.5, 0.6, 0.7]
# iou_threshold = 0.3

boxes = np.array([
    [100, 100, 210, 210],
    [105, 105, 215, 215],
    [150, 150, 250, 250]
])

scores = np.array([0.9, 0.8, 0.7])
threshold = 0.5


kept_indices = non_max_suppression(boxes, scores, threshold)
kept_boxes = [boxes[i] for i in kept_indices]

print("Kept indices:", kept_indices)
print("Kept boxes:", kept_boxes)


Kept indices: [0, 2]
Kept boxes: [array([100, 100, 210, 210]), array([150, 150, 250, 250])]
