In [2]:
import numpy as np

In [5]:
# dot of two vectors
u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,i->', u, v) # equal to dot u and v
print(r)

11


In [6]:
# Sum of two vectors
u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,j->i', u, v) # equal to multiply vector u with sum of vector v
print(r)

[18 12 24  6]


In [7]:
u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,j->j', u, v) # Same as above with reverse order
print(r)

[20 10  0 30]


In [9]:
u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,j->ij', u, v) # Outer product
print(r)

[[ 6  3  0  9]
 [ 4  2  0  6]
 [ 8  4  0 12]
 [ 2  1  0  3]]


In [10]:
A = np.array([[0, 2, 1],
              [3, 1, 4]])
T = np.einsum('ij->ji', A) # Transpose
print(T)

[[0 3]
 [2 1]
 [1 4]]


In [12]:
A = np.array([[5, 2, 1],
              [3, 1, 6],
              [2, 4, 3]])
r = np.einsum('ii->i', A) # Taking diagonal elements
print(r)

[5 1 3]


In [13]:
A = np.array([[5, 2, 1],
              [3, 1, 6],
              [2, 4, 3]])
r = np.einsum('ii->', A) # Sum of diagonal elements
print(r)

9


In [14]:
A = np.array([[3, 0, 1],
              [2, 2, 3]])
B = np.array([[1, 0, 2],
              [3, 2, 1]])
r = np.einsum('ij,ij->ij', A, B) # Matrix multiplication
print(r)

[[3 0 2]
 [6 4 3]]


In [15]:
A = np.array([[0, 2, 1],
              [3, 1, 4]])
B = np.array([[2, 5],
              [0, 1],
              [3, 4]])
C = np.einsum('ij,jk->ik', A, B) # dot product of A and B
print(C)

[[ 3  6]
 [18 32]]
