In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

import pandas as pd


In [14]:
iris = pd.read_csv('iris_1D.csv')

# Seperating the data into dependent and independent variables
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:, -1].values

In [15]:
X_train[:,0]

array([1.4, 1. , 1.3, 1.9, 2. , 3.8, 4.1, 3.9, 4.2, 3.4])

In [16]:
y_train

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [17]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [18]:
# predict
x_test = np.array([[3.0]])
clf.predict_proba(x_test)

array([[0.0454125, 0.9545875]])

In [19]:
clf.class_count_

array([5., 5.])

In [20]:
clf.class_prior_

array([0.5, 0.5])

In [21]:
clf.var_

array([[0.1416],
       [0.0776]])

In [22]:
clf.theta_

array([[1.52],
       [3.88]])

Manually computute

In [23]:
import math
import numpy as np

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [27]:
# compute Gaussian for group 1
data_c0 = np.array([1.4, 1.0, 1.3, 1.9, 2.0])
mean_c0 = data_c0.mean()
print(mean_c0)
var_c0  = data_c0.var()
print(var_c0)

1.52
0.1416


In [28]:
# compute Gaussian for group 2
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
print(mean_c1)
var_c1  = data_c1.var()
print(var_c1)
prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)
print(prob_c1)

3.88
0.07760000000000002
[1.37426395 1.0484362  1.42843305 0.74034542 0.3245289 ]


In [26]:
# predict manually
x_test = np.array([[3.0]])
pdf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
pdf_c1_x = gaussian_function(x_test, mean_c1, var_c1)

# normalize
total = pdf_c0_x*0.5 + pdf_c1_x*0.5

pdf_c0_x = pdf_c0_x*0.5/total
pdf_c1_x = pdf_c1_x*0.5/total
print(pdf_c0_x)
print(pdf_c1_x)

[[0.0454125]]
[[0.9545875]]
