In [1]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

import pandas as pd

In [2]:
iris = pd.read_csv('iris_2D.csv')

# Seperating the data into dependent and independent variables
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:, -1].values

In [3]:
X_train[:,0]

array([4.9, 4.7, 4.6, 5. , 5.4, 4.6, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3])

In [4]:
X_train[:,1]

array([3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3])

In [5]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [6]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [7]:
# predict
x_test = np.array([[4.1, 2.9]])
clf.predict_proba(x_test)

array([[0.996191, 0.003809]])

In [8]:
clf.class_prior_

array([0.5, 0.5])

In [9]:
clf.var_

array([[0.07888889, 0.09555556],
       [0.22805556, 0.11138889]])

In [10]:
clf.theta_

array([[4.86666667, 3.36666667],
       [6.21666667, 2.91666667]])

Manually compute

In [11]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [12]:
gaussian_function(np.array([[4.1]]), 6.21666667, 0.22805556)

array([[4.52805727e-05]])

In [13]:
gaussian_function(np.array([[2.9]]), 2.91666667, 0.11138889)

array([[1.19384409]])

In [14]:
# group 1

data_c0 = np.array([4.9, 4.7, 4.6, 5. , 5.4, 4.6])
mean_c0 = data_c0.mean()
var_c0  = data_c0.var()
print(mean_c0)
print(var_c0)      

prob_c0 = gaussian_function(data_c0, mean_c0, var_c0)
print(prob_c0)

4.866666666666667
0.07888888888888902
[1.41040466 1.19108252 0.90503169 1.26901734 0.2341255  0.90503169]


In [15]:
# Group 2
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
var_c1  = data_c1.var()
print(mean_c1)
print(var_c1)

prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)
print(prob_c1)

3.88
0.07760000000000002
[1.37426395 1.0484362  1.42843305 0.74034542 0.3245289 ]


In [16]:
# predict manually

x_test = np.array([[3.0]])
dpf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
dpf_c1_x = gaussian_function(x_test, mean_c1, var_c1)
print(dpf_c0_x)
print(dpf_c1_x)

# normalize
total = dpf_c0_x*0.5 + dpf_c1_x*0.5
print(total)
dpf_c0_x = dpf_c0_x*0.5/total
dpf_c1_x = dpf_c1_x*0.5/total

# print
print(dpf_c0_x)
print(dpf_c1_x)

[[3.64101612e-10]]
[[0.00974954]]
[[0.00487477]]
[[3.73455214e-08]]
[[0.99999996]]
